from dietz.songs import Song, Author, Songbook

def generate_song_pages(songs: list[Song], authors: list[Author], songbook: Songbook): ...

def generate_category_pages(songs: list[Song], authors: list[Author], songbook: Songbook): ...

def generate_author_pages(songs: list[Song], authors: list[Author], songbook: Songbook): ...

def generate_songbook_index(songs: list[Song], authors: list[Author], songbook: Songbook): ...

def generate_global_index(songs: list[Song], authors: list[Author], songbooks: list[Songbook]): ...
